// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  if (!Cards) {
    throw "Hey, where are my Cards?";
  }

  if (!Comments) {
    throw "Look, I need those Comments, too!";
  }

  Comments.after.insert(function(userId, comment) {
    var card, cardId;
    cardId = comment.cardId;
    card = Cards.findOne(cardId);
    if (__indexOf.call(card.memberIds, userId) < 0) {
      return Cards.update(cardId, {
        $addToSet: {
          memberIds: userId
        }
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=plugin.map
*/
